apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend-app
        image: gcr.io/todo-frontend-315708/backend
        imagePullPolicy: Always

        ports:
        - containerPort: 8080
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs